### ISSUE TITLE
[Dotaz] Generování QR kódu

### ISSUE THREAD

**Issue by Rohlik** [mikrop/qreet-java#1]
Hledám způsob jak ze vstupu (datum, čas, částka, BKP) vygenerovat QR kód pro potřeby účtenovky. Pomůžemi s tím táto utilitka?
Přiznám se, že jsem Javou nepolíbený, takže se omlouvám předem za amatérský dotaz.

Děkuji předem.

**Comment by mikrop** [comment]
Ano, tato knihovna řeší přesně tento problém. 
Použití je pak velmi jednoduché, viz. následující příklad: 

> EetUctenka uctenka = EetUctenka.ofBkp(
"6455B192-D697186A-6AB1971A-1E9B146B-CDD5007B", // Kód BKP
null, // Nepovinný parametr DIČ
34113.00d, // Částka
new Date(), // Datum s časem
Rezim.BEZNY // Režim tržby
);
String text = uctenka.generateString();
File file = QRCode.from(text).to(ImageType.JPG).file("QRBkp.jpg");

**Comment by mikrop** [comment]
Ano, tato knihovna řeší přesně tento problém.
Použití je pak velmi jednoduché, viz. následující příklad:

```java
EetUctenka uctenka = EetUctenka.ofBkp(
        "6455B192-D697186A-6AB1971A-1E9B146B-CDD5007B", // Kód BKP
        null, // Nepovinný parametr DIČ
        34113.00d, // Částka
        new Date(), // Datum s časem
        Rezim.BEZNY // Režim tržby (BEZNY, nebo ZJEDNODUSENY)
);
QRCode.from(uctenka).writeTo(new FileOutputStream("C:/tmp/QRBKP.jpg")); 
```
